"""Bearer token authentication for API endpoints."""

import logging
import math
import re
import secrets
from fastapi import Request, HTTPException, status
from app.config import settings

logger = logging.getLogger(__name__)

# Strict bearer header: scheme + single space + token chars only.
_BEARER_RE = re.compile(r'^Bearer ([A-Za-z0-9_=+/.\-]+)$')

_INSECURE_DEFAULT_TOKENS = {
    "",
    "change-me",
    "change-me-to-secure-token",
    "change-me-to-a-secure-random-token",  # .env.example default
}


def _extract_bearer(request: Request) -> str | None:
    """Strict Bearer header parsing — single space, allowed token charset."""
    auth = request.headers.get("Authorization", "")
    m = _BEARER_RE.match(auth)
    return m.group(1) if m else None


def _shannon_bits(s: str) -> float:
    """Approximate Shannon entropy in bits for a token."""
    if not s:
        return 0.0
    from collections import Counter
    counts = Counter(s)
    total = len(s)
    return -sum(
        (c / total) * math.log2(c / total) for c in counts.values()
    ) * total


async def verify_token(request: Request) -> str:
    """
    Verify the bearer token supplied in the Authorization header.
    Compared in constant time. Refuses insecure defaults and low-entropy tokens.
    """
    expected = (settings.internal_token or "").strip()
    if expected in _INSECURE_DEFAULT_TOKENS:
        logger.critical("INTERNAL_TOKEN is unset or insecure — rejecting request")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Service token is not configured",
        )

    # Require at least 32 chars and ~96 bits of Shannon entropy.
    # Generated by `python3 -c "import secrets; print(secrets.token_urlsafe(48))"`
    # this comfortably exceeds the bar.
    if len(expected) < 32 or _shannon_bits(expected) < 96.0:
        logger.error("INTERNAL_TOKEN entropy too low — refusing to start")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Service token is not configured",
        )

    provided = _extract_bearer(request)
    if not provided:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing bearer token",
            headers={"WWW-Authenticate": "Bearer"},
        )

    if not secrets.compare_digest(provided, expected):
        client_ip = request.client.host if request.client else "unknown"
        logger.warning("Invalid token from %s", client_ip)
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Invalid service token",
        )

    return "authenticated"
